// ReSharper disable InconsistentNaming — opcode names match the TT spec literally.
namespace SharpAstro.Fonts.Hinting;

/// <summary>
/// TrueType bytecode opcodes, named per the official spec. Many opcodes
/// pack a small bitfield into the lower bits of the byte (e.g. PUSHB[abc]
/// packs the count - 1 in the low 3 bits); only the base name is in this
/// enum and the dispatcher decodes the bitfield separately.
/// </summary>
internal enum Op : byte
{
    SVTCA_y       = 0x00,
    SVTCA_x       = 0x01,
    SPVTCA_y      = 0x02,
    SPVTCA_x      = 0x03,
    SFVTCA_y      = 0x04,
    SFVTCA_x      = 0x05,
    SPVTL_min     = 0x06,
    SPVTL_max     = 0x07,
    SFVTL_min     = 0x08,
    SFVTL_max     = 0x09,
    SPVFS         = 0x0A,
    SFVFS         = 0x0B,
    GPV           = 0x0C,
    GFV           = 0x0D,
    SFVTPV        = 0x0E,
    ISECT         = 0x0F,

    SRP0          = 0x10,
    SRP1          = 0x11,
    SRP2          = 0x12,
    SZP0          = 0x13,
    SZP1          = 0x14,
    SZP2          = 0x15,
    SZPS          = 0x16,
    SLOOP         = 0x17,
    RTG           = 0x18,
    RTHG          = 0x19,
    SMD           = 0x1A,
    ELSE          = 0x1B,
    JMPR          = 0x1C,
    SCVTCI        = 0x1D,
    SSWCI         = 0x1E,
    SSW           = 0x1F,

    DUP           = 0x20,
    POP           = 0x21,
    CLEAR         = 0x22,
    SWAP          = 0x23,
    DEPTH         = 0x24,
    CINDEX        = 0x25,
    MINDEX        = 0x26,
    ALIGNPTS      = 0x27,
    UTP           = 0x29,
    LOOPCALL      = 0x2A,
    CALL          = 0x2B,
    FDEF          = 0x2C,
    ENDF          = 0x2D,
    MDAP_min      = 0x2E,
    MDAP_max      = 0x2F,

    IUP_y         = 0x30,
    IUP_x         = 0x31,
    SHP_min       = 0x32,
    SHP_max       = 0x33,
    SHC_min       = 0x34,
    SHC_max       = 0x35,
    SHZ_min       = 0x36,
    SHZ_max       = 0x37,
    SHPIX         = 0x38,
    IP            = 0x39,
    MSIRP_min     = 0x3A,
    MSIRP_max     = 0x3B,
    ALIGNRP       = 0x3C,
    RTDG          = 0x3D,
    MIAP_min      = 0x3E,
    MIAP_max      = 0x3F,

    NPUSHB        = 0x40,
    NPUSHW        = 0x41,
    WS            = 0x42,
    RS            = 0x43,
    WCVTP         = 0x44,
    RCVT          = 0x45,
    GC_cur        = 0x46,
    GC_orig       = 0x47,
    SCFS          = 0x48,
    MD_cur        = 0x49,
    MD_orig       = 0x4A,
    MPPEM         = 0x4B,
    MPS           = 0x4C,
    FLIPON        = 0x4D,
    FLIPOFF       = 0x4E,
    DEBUG         = 0x4F,

    LT            = 0x50,
    LTEQ          = 0x51,
    GT            = 0x52,
    GTEQ          = 0x53,
    EQ            = 0x54,
    NEQ           = 0x55,
    ODD           = 0x56,
    EVEN          = 0x57,
    IF            = 0x58,
    EIF           = 0x59,
    AND           = 0x5A,
    OR            = 0x5B,
    NOT           = 0x5C,
    DELTAP1       = 0x5D,
    SDB           = 0x5E,
    SDS           = 0x5F,

    ADD           = 0x60,
    SUB           = 0x61,
    DIV           = 0x62,
    MUL           = 0x63,
    ABS           = 0x64,
    NEG           = 0x65,
    FLOOR         = 0x66,
    CEILING       = 0x67,
    ROUND_grey    = 0x68,
    ROUND_black   = 0x69,
    ROUND_white   = 0x6A,
    ROUND_unused  = 0x6B,
    NROUND_grey   = 0x6C,
    NROUND_black  = 0x6D,
    NROUND_white  = 0x6E,
    NROUND_unused = 0x6F,

    WCVTF         = 0x70,
    DELTAP2       = 0x71,
    DELTAP3       = 0x72,
    DELTAC1       = 0x73,
    DELTAC2       = 0x74,
    DELTAC3       = 0x75,
    SROUND        = 0x76,
    S45ROUND      = 0x77,
    JROT          = 0x78,
    JROF          = 0x79,
    ROFF          = 0x7A,
    RUTG          = 0x7C,
    RDTG          = 0x7D,
    SANGW         = 0x7E,
    AA            = 0x7F,

    FLIPPT        = 0x80,
    FLIPRGON      = 0x81,
    FLIPRGOFF     = 0x82,
    SCANCTRL      = 0x85,
    SDPVTL_min    = 0x86,
    SDPVTL_max    = 0x87,
    GETINFO       = 0x88,
    IDEF          = 0x89,
    ROLL          = 0x8A,
    MAX           = 0x8B,
    MIN           = 0x8C,
    SCANTYPE      = 0x8D,
    INSTCTRL      = 0x8E,
    GETVAR        = 0x91,
    GETDATA       = 0x92,

    // PUSHB[abc] = 0xB0..0xB7 (n = abc + 1 byte operands)
    PUSHB_base    = 0xB0,
    // PUSHW[abc] = 0xB8..0xBF (n = abc + 1 word operands)
    PUSHW_base    = 0xB8,
    // MDRP[abcde] = 0xC0..0xDF
    MDRP_base     = 0xC0,
    // MIRP[abcde] = 0xE0..0xFF
    MIRP_base     = 0xE0,
}
