namespace SharpAstro.Fonts.Shaping.Ucd;

/// <summary>
/// Canonical Combining Class (CCC) lookup — the Unicode property that drives canonical mark
/// ordering (a run of combining marks is stable-sorted by CCC so below/above marks end up in
/// a deterministic order regardless of typed sequence). The shaper uses it to reorder marks
/// before applying GPOS, matching the order HarfBuzz produces from its normalizer.
///
/// <para>The data (<see cref="Ranges"/>) is the full UCD-wide table, generated by
/// <c>tools/UcdGen</c> from <c>UnicodeData.txt</c> — every codepoint with a nonzero CCC, not
/// just the Latin/Greek block H2 hand-transcribed. Codepoints outside every range are
/// starters (CCC 0), which never reorder.</para>
/// </summary>
internal static partial class CanonicalCombiningClass
{
    /// <summary>The canonical combining class of <paramref name="codepoint"/>: 0 for starters
    /// (base letters, spaces, and any codepoint not in the table), &gt;0 for combining marks
    /// that participate in canonical ordering.</summary>
    public static byte Get(uint codepoint) => UcdTables.RangeByte(Ranges, codepoint, notFound: 0);
}
