namespace SharpAstro.Fonts.Shaping;

/// <summary>
/// Canonical Combining Class (CCC) lookup — the Unicode property that drives canonical
/// mark ordering (a run of combining marks is stable-sorted by CCC so below/above marks
/// end up in a deterministic order regardless of typed sequence). The shaper uses it to
/// reorder marks before applying GPOS, matching the order HarfBuzz produces from its
/// normalizer.
///
/// <para><b>Coverage:</b> the Combining Diacritical Marks block <c>U+0300–U+036F</c>,
/// which holds the accents Latin and Greek text use (the plan's primary mark scripts).
/// Everything outside the block returns 0 (a "starter" — never reordered), which is the
/// safe degradation: well-formed input is left in typed order. The complete UCD-wide CCC
/// table (Cyrillic, Hebrew points, symbols) is generated by the offline <c>UcdGen</c>
/// tool at H4; H2 ships the block that covers the scripts it positions.</para>
///
/// <para>Values transcribed from <c>DerivedCombiningClass</c> / <c>UnicodeData</c> (UCD
/// 17.0, stable for this block across versions). Stored as an RVA blob
/// (<see cref="System.ReadOnlySpan{T}"/> over the assembly data section) — no allocation,
/// AOT-friendly.</para>
/// </summary>
internal static class CanonicalCombiningClass
{
    private const uint BlockStart = 0x0300;
    private const uint BlockEnd = 0x036F; // inclusive

    // CCC for U+0300..U+036F, one byte per codepoint (112 entries, 8 per row).
    private static ReadOnlySpan<byte> Block =>
    [
        230, 230, 230, 230, 230, 230, 230, 230, // 0300-0307
        230, 230, 230, 230, 230, 230, 230, 230, // 0308-030F
        230, 230, 230, 230, 230, 232, 220, 220, // 0310-0317
        220, 220, 232, 216, 220, 220, 220, 220, // 0318-031F
        220, 202, 202, 220, 220, 220, 220, 202, // 0320-0327
        202, 220, 220, 220, 220, 220, 220, 220, // 0328-032F
        220, 220, 220, 220,   1,   1,   1,   1, // 0330-0337
          1, 220, 220, 220, 220, 230, 230, 230, // 0338-033F
        230, 230, 230, 230, 230, 240, 230, 220, // 0340-0347
        220, 220, 230, 230, 230, 220, 220,   0, // 0348-034F (034F = CGJ, CCC 0)
        230, 230, 230, 220, 220, 220, 220, 230, // 0350-0357
        232, 220, 220, 230, 233, 234, 234, 233, // 0358-035F
        234, 234, 233, 230, 230, 230, 230, 230, // 0360-0367
        230, 230, 230, 230, 230, 230, 230, 230, // 0368-036F
    ];

    /// <summary>
    /// The canonical combining class of <paramref name="codepoint"/>: 0 for starters
    /// (base letters, spaces, and any codepoint outside the supported block), &gt;0 for
    /// combining marks that participate in canonical ordering.
    /// </summary>
    public static byte Get(uint codepoint)
        => codepoint is >= BlockStart and <= BlockEnd ? Block[(int)(codepoint - BlockStart)] : (byte)0;
}
